services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Pixelant\PxaProductManager\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Service/LinkBuilders/*'

  Pixelant\PxaProductManager\Attributes\ValueUpdater\UpdaterInterface:
    class: Pixelant\PxaProductManager\Attributes\ValueUpdater\ValueUpdaterService

  Pixelant\PxaProductManager\Command\UpdateInheritanceCommand:
    tags:
      - name: 'console.command'
        command: 'productmanager:updateinheritance'

  Pixelant\PxaProductManager\Command\UpdateRelationInheritanceIndexCommand:
    tags:
      - name: 'console.command'
        command: 'productmanager:updaterelationinheritanceindex'

  Pixelant\PxaProductManager\Command\FixDuplicateAttributeValuesCommand:
    tags:
      - name: 'console.command'
        command: 'productmanager:fixduplicateattributevalues'

  Pixelant\PxaProductManager\Command\RemoveOrphanAttributeValuesCommand:
    tags:
      - name: 'console.command'
        command: 'productmanager:removeorphanattributevalues'

  Pixelant\PxaProductManager\Event\DataInheritance\CalculateInlineFieldFileReferenceValueEvent:
    tags:
      - name: event.listener
        identifier: 'calculateInlineFieldFileReferenceValueEvent'
        before: ''
        event: Pixelant\PxaProductManager\Event\DataInheritance\CalculateInlineFieldValueEvent

  Pixelant\PxaProductManager\Event\DataInheritance\CalculateInlineFieldLinkValueEvent:
    tags:
      - name: event.listener
        identifier: 'calculateInlineFieldLinkValueEvent'
        before: ''
        event: Pixelant\PxaProductManager\Event\DataInheritance\CalculateInlineFieldValueEvent

  Pixelant\PxaProductManager\Event\DataInheritance\CalculateInlineFieldAttributeValueValueEvent:
    tags:
      - name: event.listener
        identifier: 'calculateInlineFieldAttributeValueValueEvent'
        before: ''
        event: Pixelant\PxaProductManager\Event\DataInheritance\CalculateInlineFieldValueEvent

  Pixelant\PxaProductManager\Event\DataInheritance\InheritNewInlineFileReferenceDataEvent:
    tags:
      - name: event.listener
        identifier: 'inheritNewInlineFileReferenceDataEvent'
        before: ''
        event: Pixelant\PxaProductManager\Event\DataInheritance\InheritNewInlineDataEvent

  Pixelant\PxaProductManager\Event\DataInheritance\InheritNewInlineLinkDataEvent:
    tags:
      - name: event.listener
        identifier: 'inheritNewInlineLinkDataEvent'
        before: ''
        event: Pixelant\PxaProductManager\Event\DataInheritance\InheritNewInlineDataEvent

  Pixelant\PxaProductManager\Event\DataInheritance\InlineLinkIdentifierFieldEvent:
    tags:
      - name: event.listener
        identifier: 'inlineLinkIdentifierFieldEvent'
        before: ''
        event: Pixelant\PxaProductManager\Event\DataInheritance\InlineIdentifierFieldEvent

  Pixelant\PxaProductManager\Event\DataInheritance\InlineAttributeValueIdentifierFieldEvent:
    tags:
      - name: event.listener
        identifier: 'inlineAttributeValueIdentifierFieldEvent'
        before: ''
        event: Pixelant\PxaProductManager\Event\DataInheritance\InlineIdentifierFieldEvent


  Pixelant\PxaProductManager\EventListener\CacheWarmupEventListener:
    tags:
      - name: event.listener
        identifier: 'pxa-product-manager-cache-warmup'
        event: TYPO3\CMS\Core\Cache\Event\CacheWarmupEvent

  Pixelant\PxaProductManager\EventListener\BootCompletedEventListener:
    tags:
      - name: event.listener
        identifier: 'pxa-product-manager-boot-completed'
        event: TYPO3\CMS\Core\Core\Event\BootCompletedEvent
